# whale-net scala pre-commit v1

repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        # -   id: check-yaml
        - id: check-added-large-files
        - id: mixed-line-ending
          args: [ --fix=lf ]
#  - repo: git@github.com:coyainsurance/pre-commit-scalafmt.git
#    rev: 1.0.1
#    hooks:
#      - id: scalafmt
#        args: [ -p9090, -t ] # run in server mode on port 9090 and pass `--test` to scalafmt; alternatively you can place here other supported cmdline arguments
