apiVersion: v1
kind: Service
metadata:
  name: plant-lab-service
  namespace: {{ .Values.namespace }}
  labels:
    app: plant-lab
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: plant-lab